import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Menu from "./Components/MenuComponents/MenuComponent"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout(){
  {
    return (
      <html lang="en">
        <header style={{ borderStyle: 'double', height : '100%' }}><Menu/></header>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
       
        </body>
      </html>
    );
  }
}
